# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  BeforeInstall:
    - location: scripts-deploy/before.sh
  AfterInstall:
    - location: scripts-deploy/after.sh